#!/bin/bash

set -e

install-info --delete --info-dir='/usr/share/info' '/usr/share/info/make.info'
install-info --delete --info-dir='/usr/share/info' '/usr/share/info/make.info-1'
install-info --delete --info-dir='/usr/share/info' '/usr/share/info/make.info-2'