#!/bin/bash

set -e

install-info --info-dir='/usr/share/info' '/usr/share/info/tar.info'
install-info --info-dir='/usr/share/info' '/usr/share/info/tar.info-1'
install-info --info-dir='/usr/share/info' '/usr/share/info/tar.info-2'