#!/bin/bash

set -e

install-info --info-dir='/usr/share/info' '/usr/share/info/gnupg.info'
install-info --info-dir='/usr/share/info' '/usr/share/info/gnupg.info-1'
install-info --info-dir='/usr/share/info' '/usr/share/info/gnupg.info-2'