#!/bin/bash

set -e

install-info --delete --info-dir='/usr/share/info' '/usr/share/info/gmp.info'
install-info --delete --info-dir='/usr/share/info' '/usr/share/info/gmp.info-1'
install-info --delete --info-dir='/usr/share/info' '/usr/share/info/gmp.info-2'