#!/bin/bash

set -e

install-info --delete --info-dir='/usr/share/info' '/usr/share/info/grub.info'
install-info --delete --info-dir='/usr/share/info' '/usr/share/info/grub.info-1'
install-info --delete --info-dir='/usr/share/info' '/usr/share/info/grub.info-2'
install-info --delete --info-dir='/usr/share/info' '/usr/share/info/grub-dev.info'