#!/bin/bash

set -e

install-info --info-dir='/usr/share/info' '/usr/share/info/gcrypt.info'
install-info --info-dir='/usr/share/info' '/usr/share/info/gcrypt.info-1'
install-info --info-dir='/usr/share/info' '/usr/share/info/gcrypt.info-2'