#!/bin/bash

set -e

install-info --delete --info-dir='/usr/share/info' '/usr/share/info/m4.info'
install-info --delete --info-dir='/usr/share/info' '/usr/share/info/m4.info-1'
install-info --delete --info-dir='/usr/share/info' '/usr/share/info/m4.info-2'